### ISSUE TITLE
Use maintained deemix

### ISSUE THREAD

**Issue by Gauvino** [codefaux/deemix-for-lidarr#12]
https://github.com/bambanah/deemix
This repo is a revived project for deemix and swithcing to it would be very cool since deemix is full of many bugs

**Comment by codefaux** [comment]
Sorry, somehow I lost track of the notification on this. Can you confirm that you've tested the Lidarr plugins interaction with the new Docker image? Do other changes need to be made? I'd like to implement this, but it would involve a full re-deploy on my end and I'm a bit busy ATM. If you can create a pull request I'll look it over, otherwise it'll be a short while. Ping me if you don't hear back for a while.

**Comment by codefaux** [comment]
So the short version is, to switch to the maintained version of Deemix, just change the image you're using in docker-compose. Using the bambanah version of Deemix which you've linked, alongside the plugins-enabled Lidarr instance, is enough. My project does not need to be involved; it was just an ugly bugfix and an example docker-compose.yml

Below is a fully functional docker-compose.yml -- I've changed the config volume to `/config` on the container side as the new container defaults to that. `UMASK` to `UMASK_SET` and added `DEEMIX_SINGLE_USER=true` in the `environment` section, as well as adding the previously-missing library directory, but otherwise it's the same.

```
name: deemix-for-lidarr
services:
  deemix:
    container_name: deemix
    image: ghcr.io/bambanah/deemix:latest
    environment:
      - PUID=100
      - PGID=99
      - UMASK_SET=0022
      - TZ=Etc/UTC
      - DEEMIX_SINGLE_USER=true
    volumes:
      - /docker/deemix/downloads:/downloads
      - /docker/deemix/config:/config
    ports:
      - 6595:6595
    restart: unless-stopped

  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:pr-plugins
    environment:
      - PUID=100
      - PGID=99
      - UMASK=0022
      - TZ=Etc/UTC
    volumes:
      - /mnt/music:/library
      - /docker/deemix/downloads:/downloads
      - /docker/lidarr/config:/config
    ports:
      - 8686:8686
    restart: unless-stopped
```
