### ISSUE TITLE
Cannot add Deemix as indexer while as DL client is fine

### ISSUE THREAD

**Issue by etique57** [codefaux/deemix-for-lidarr#8]
Hello,

I just installed everything following your very good documentation, but I'm unable to add Deemix as an indexer while everything is fine for the Download Client.

Error is the following:
![image](https://github.com/user-attachments/assets/ebf037bb-c2e3-4255-b9f0-69696e9e6c77)

I'm using the same hostname for both the DL Client and the indexer (deemix) but replacing it by external hostnames or IP is not helping.

Here's my docker-compose:
```
  lidarr:
    container_name: lidarr
    # image: lscr.io/linuxserver/lidarr:latest
    image: ghcr.io/hotio/lidarr:pr-plugins
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=0022
      - TZ=Europe/Paris
    volumes:
      - /opt/appdata/lidarr/config:/config
      - /mnt/storage/music:/music
      - /mnt/storage/deluge/seed:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8686:8686
    restart: unless-stopped
    
  deemix:
    container_name: deemix
    image: codefaux/deemix-for-lidarr
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=0022
      - TZ=Europe/Paris
    volumes:
      - /mnt/storage/deemix/downloads:/downloads
      - /opt/appdata/deemix/config:/deemix-gui/config
    ports:
      - 6595:6595
    restart: unless-stopped
```
